spring:
  rabbitmq:
    host: localhost
    port: 5672

rabbitmq:
  vacancies_queue: imported-vacancies-queue
  vacancies_imported_exchange: imported-vacancies-exchange
  vacancy_import_scheduled_tasks_queue: vacancy-import-scheduled-tasks-queue

api:
  url: https://api.hh.ru/vacancies/